//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by e:\projects\dirtyJOE\dirtyJOE\dirtyJOE.rc
//
#define DJ_MAIN_DLG                     101
#define DJ_CPOOL_TAB_DLG                102
#define IDR_MAIN_MENU                   103
#define DJ_FIELDS_TAB_DLG               104
#define DJ_FIELDS_SUB_TAB_DLG           105
#define DJ_CODE_DLG                     106
#define DJ_LB_DLG                       107
#define DJ_MAIN_TAB_DLG                 108
#define DJ_EDIT_UTF8                    109
#define DJ_EDIT_Ux                      110
#define DJ_EDIT_VAL                     111
#define DJ_EDIT_REF                     112
#define DJ_ADD_CP                       113
#define DJ_CODE_MOD                     114
#define DJ_MINI_HEX_EDIT                115
#define DJ_ABOUT                        116
#define IDB_BITMAP1                     118
#define IDI_ICON1                       123
#define DJ_SIMPLE_DEC_EDIT              124
#define DJ_EDIT_FLAGS                   125
#define IDR_CTX_MENU                    126
#define DJ_EDIT_INNERCLS                127
#define DJ_EDIT_ATTR_EXCEPTIONS         128
#define DJ_EDIT_EXCEPTION               129
#define DJ_MAIN_TOTALCMD                130
#define IDR_MENU1                       130
#define IDR_MENU2                       131
#define DJ_SETTINGS                     133
#define DJ_PYDECRYPT                    134
#define IDD_DIALOG1                     135
#define DJ_PYMULTIDECRYPT               135
#define IDD_DIALOG2                     136
#define DJ_SELECT_COLUMN                136
#define DJ_OPCODE_HELP                  137
#define IDB_BITMAP2                     140
#define DJ_EDIT_LOCALVARS               141
#define DJ_RESTORE_DEBUG                142
#define ACCEL_DLGMAIN                   144
#define DJ_MAIN_TAB                     1001
#define CPTAB_LB                        1002
#define IDC_MN_GRP                      1003
#define IDC_EDIT_MAGIC                  1004
#define IDC_EDIT_MINOR                  1005
#define IDC_EDIT_MAJOR                  1006
#define IDC_EDIT_ACCF                   1007
#define IDC_EDIT_THIS                   1008
#define IDC_EDIT_SUPER                  1009
#define IDC_EDIT_CPC                    1010
#define IDC_EDIT_FLAGS                  1011
#define IDC_EDIT_INTC                   1012
#define IDC_EDIT_DESCRIPTOR             1013
#define IDC_EDIT_FILC                   1014
#define IDC_EDIT_DEMANGLED              1015
#define IDC_EDIT_METHC                  1016
#define IDC_EDIT_ATTC                   1017
#define LB_INTERFACES                   1018
#define IDC_FIELD_GRP                   1019
#define LB_ATTRIBUTES                   1020
#define IDC_EDIT_NAME                   1021
#define LB_ATTRIBS                      1022
#define IDC_EDIT_LOCALS                 1023
#define LB_ATTRIBS_PROPS                1025
#define IDC_EDIT_CODE_SIZE              1025
#define IDC_EDIT_STACK                  1026
#define LB_DJ_LB                        1027
#define IDC_EDIT_ATTRS                  1027
#define BTN_CP_EDIT                     1028
#define IDC_EDIT_EXCS                   1028
#define EDT_UTF8                        1029
#define BTN_CP_SHOWREF                  1029
#define BTN_SHOW_REF                    1030
#define BTN_CANCEL                      1031
#define BTN_SAVE                        1032
#define BTN_CP_ADD                      1033
#define BTN_CP_SEARCH                   1035
#define CB_EDIT                         1039
#define EDIT_DEC                        1043
#define EDIT_HEX                        1044
#define CHECK_HEX                       1048
#define CHECK_DEC                       1049
#define CB_EDIT_1                       1049
#define CB_EDIT_2                       1050
#define STATIC_CB_1                     1051
#define STATIC_CB_2                     1052
#define LB_EXCS                         1052
#define LB_ATTRS                        1053
#define IDC_STATIC_ATTR                 1054
#define CB_ADD_CP                       1055
#define BTN_ADD_CP                      1057
#define LB_ADDR                         1058
#define LB_HEX                          1059
#define LB_DISASM                       1060
#define EDT_HEX                         1064
#define TXT_VERSION                     1068
#define TXT_WWW                         1069
#define TXT_MAIL                        1070
#define TXT_INSTR                       1070
#define BMP_LOGO                        1071
#define TXT_ESTLEN                      1072
#define BTN_EDIT_MIN_VER                1072
#define BMP_DONATE                      1072
#define BTN_EDIT_MAJ_VER                1073
#define BTN_EDIT_ACCESS_FLAGS           1074
#define CHK_PUBLIC                      1074
#define BTN_EDIT_THIS_CLASS             1075
#define CHK_FINAL                       1075
#define BTN_EDIT_SUPER_CLASS            1076
#define CHK_SUPER                       1076
#define CHK_INTERFACE                   1077
#define CHK_ABSTRACT                    1078
#define CHK_SYNTHETIC                   1079
#define CHK_ANNOTATION                  1080
#define CHK_ENUM                        1081
#define CHK_PRIVATE                     1082
#define CHK_PROTECTED                   1083
#define CMB_CP_FILTER                   1083
#define CHK_STATIC                      1084
#define CHK_VOLATILE                    1085
#define TXT_OBJ_FILTER                  1085
#define CHK_TRANSIENT                   1086
#define LB_INNERCLS                     1086
#define CHK_NATIVE                      1087
#define EDT_IC_INFO_INDEX               1087
#define CHK_STRICT                      1088
#define EDT_OC_INFO_INDEX               1088
#define EDT_FLAGS_RAW                   1089
#define EDT_IC_NAME_INDEX               1089
#define EDT_IC_ACC_FLAGS                1090
#define BTN_IC_INFO_INDEX               1091
#define BTN_OC_INFO_INDEX               1092
#define BTN_IC_NAME_INDEX               1093
#define BTN_IC_ACC_FLAGS                1094
#define BTN_IC_ADD                      1095
#define BTN_EDIT_NAME                   1096
#define BTN_IC_DEL                      1096
#define BTN_EDIT_DESCRIPTOR             1097
#define BTN_EDIT_MAXSTACK               1097
#define BTN_EDIT_NAME3                  1098
#define BTN_EDIT_FLAGS                  1098
#define BTN_EDIT_MAXLOCALS              1098
#define LB_EXCEPTIONS                   1098
#define BTN_ADD                         1099
#define BTN_DELETE                      1100
#define BTN_CLOSE                       1101
#define BTN_EDIT                        1102
#define EDT_START_PC                    1103
#define EDT_END_PC                      1104
#define EDT_LENGTH                      1104
#define EDT_HANDLER                     1105
#define EDT_INDEX                       1105
#define CMB_CATCH_TYPE                  1106
#define CB_CATCH_TYPE                   1106
#define EDT_NAME                        1106
#define BTN_OK                          1107
#define EDT_DESCRIPTOR                  1107
#define BTN_TCMD_OPTIONS                1109
#define CB_PYVER                        1110
#define CHK_UPDATE                      1111
#define CHK_SHELLEXT                    1112
#define EDT_FONT                        1113
#define BTN_FONT                        1114
#define TXT_PYSCRIPT                    1117
#define TXT_INPUTBUFFER                 1118
#define TXT_PREVIEW                     1119
#define BTN_DECRYPT                     1122
#define BTN_LOADSCRIPT                  1124
#define IDC_LIST1                       1125
#define LIST_UTF8                       1125
#define BTN_LOADSCRIPT2                 1125
#define BTN_SAVESCRIPT                  1125
#define LB_OP_LIST                      1125
#define LB_DBG_LOG                      1125
#define IDC_STATIC1                     1126
#define IDC_STATIC2                     1127
#define IDC_STATIC3                     1128
#define CHK_LOADED                      1129
#define CHK_ADDR                        1130
#define CHK_HEX                         1131
#define CHK_DISASM                      1132
#define EDT_OP_STACK                    1135
#define IDC_EDIT2                       1136
#define EDT_OP_DESCRIPTION              1136
#define EDT_STACK                       1136
#define EDT_OUTPUT_JOE                  1136
#define EDT_DESC                        1137
#define EDT_OP_NAME                     1138
#define EDT_SHORT                       1139
#define IDC_STATIC_SH                   1140
#define IDC_STATIC_FD                   1141
#define IDC_STATIC_ST                   1142
#define IDC_STATIC_NM                   1143
#define IDC_EDIT1                       1144
#define EDT_SEARCH                      1144
#define EDT_INPUT_CLASS                 1144
#define TXT_SEARCH                      1145
#define LB_LOCALVARS                    1146
#define BTN_LV_ADD                      1147
#define BTN_LV_DEL                      1148
#define BTN_LV_NAME                     1149
#define BTN_LV_DESCRIPTOR               1150
#define BTN_LV_EDITENTRY                1151
#define CHK_LOCAL_VARS                  1151
#define BTN_LV_SAVEENTRY                1152
#define CHK_RESTORE_LINES               1152
#define BTN_OUTPUT_FILE                 1153
#define IDC_BUTTON3                     1155
#define BTN_RESTORE                     1155
#define CHK_HEXIDX                      1156
#define CHK_SRCHCASE                    1157
#define BTN_PREV                        1158
#define BTN_NEXT                        1159
#define CHK_CASE                        1160
#define MENU_FILE_OPEN                  40001
#define MENU_HELP_ABOUT                 40002
#define MENU_FILE_EXIT                  40003
#define MENU_FILE_SAVE                  40004
#define MENU_HELP_HELPTOPICS            40006
#define ID_COPYTEXT                     40014
#define ID_EDITITEM                     40015
#define ID_ADDITEM                      40016
#define ID_SHOWREFERENCES               40017
#define ID_INTERFACES_ADDINTERFACE      40018
#define ID_INTERFACES_EDITINTERFACE     40019
#define ID_INTERFACES_DELETEINTERFACE   40020
#define ID_INTERFACES_COPYTEXT          40021
#define ID_ATTRIBUTES_EDITATTRIBUTE     40022
#define ID_ATTRIBUTES_ADDATTRIBUTE      40023
#define ID_ATTRIBUTES_DELETEATTRIBUTE   40024
#define ID_ATTRIBUTES_VIEWATTRIBUTE     40025
#define ID_INNERCLASSES_ADDINNERCLASS   40026
#define ID_INNERCLASSES_DELETEINNERCLASS 40027
#define ID_HELP_CHECKFORUPDATES         40028
#define MENU_HELP_CHECKFORUPDATES       40029
#define ID_OPTIONS_REGISTERSHELLEXTENSION 40030
#define MENU_OPTIONS_REGISTERSHELLEXTENSION 40031
#define ID_OPTIONS_UNREGISTERSHELLEXTENSION 40032
#define MENU_OPTIONS_UNREGISTERSHELLEXTENSION 40033
#define ID_METHODS_ADDMETHOD            40034
#define ID_METHODS_DELETEMETHOD         40035
#define ID_FIELDS_DELETEFIELD           40036
#define ID_FIELDS_ADDFIELD              40037
#define ID_CODE_EDITEXCEPTION           40039
#define ID_CODE_ADDEXCEPTION            40040
#define ID_CODE_DELETEEXCEPTION         40041
#define ID_CODE_M                       40042
#define ID_CODE_MOVEDOWN                40043
#define ID_CODE_MOVEUP                  40044
#define ID_TCMD_SAVEFILE                40049
#define ID_TCMD_HELPTOPICS              40050
#define ID_TCMD_CHECKFORUPDATES         40051
#define ID_TCMD_ABOUT                   40052
#define ID_TCMD_SETTINGS                40056
#define ID_OPTIONS_SETTINGS             40057
#define MENU_OPTIONS_SETTINGS           40058
#define ID_CP_RUNPYTHONSCRIPT           40059
#define ID_RUNPYTHONSCRIPT              40060
#define ID_CP_                          40061
#define ID_CP_RUNPYTHONSCRIPTONALLUTF8OBJECTS 40062
#define ID_RUNPYTHONSCRIPTONALLUTF8OBJECTS 40063
#define ID_ATTRIB_COPYSELECTION         40064
#define ID_ATTRIB_COPYALL               40065
#define ID_CODE_COPYSELECTION           40066
#define ID_CODE_COPYALL                 40067
#define ID_CODE_OPCODEDESCRIPTION       40068
#define ID_HELP_OPCODESHELP             40069
#define MENU_HELP_OPCODESHELP           40070
#define ID_TCMD_OPCODESHELP             40071
#define ID_HELP_DONATE                  40072
#define MENU_HELP_DONATE                40073
#define ID_TCMD_DONATE                  40074
#define ID_TOOLS_ADDLINENUMBERS         40075
#define MENU_TOOLS_ADDLINENUMS          40076
#define ID_LOCALVARS_ADDLOCALVARIABLE   40077
#define ID_LOCALVARS_DELETELOCALVARIABLE 40078
#define ID_CODE_EDITOPCODE              40079
#define ID_CODE_ADDEXCEPTIONHANDLERFORSELECTEDCODE 40080
#define ID_FILE_RECENTFILES             40081
#define ID_CODE_FIND                    40082
#define ID_TCMD_RESTOREDEBUGINFO        40088
#define ID_CODE_COPY                    40089
#define ID_CODE_COPY40090               40090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40097
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
